### ISSUE TITLE
Installation issue on GPU version

### ISSUE THREAD

**Issue by rmcao** [flatironinstitute/jax-finufft#46]
Hi, 

I'm trying to set up for the GPU version. I used jax & jaxlib 0.4.10 (also tested other versions like 0.4.21 or 0.3.18), CUDA 11.8, and CMAKE_ARGS "-DCMAKE_CUDA_ARCHITECTURES=89 -DJAX_FINUFFT_USE_CUDA=ON" (based on the RTX4090 I'm using). I followed the setup instructions in the README but I kept getting the following error when running the example script (it was fine in the CPU version):

```
>>> import numpy as np
>>> from jax_finufft import nufft1
>>> 
>>> M = 100000
>>> N = 200000
>>> 
>>> x = 2 * np.pi * np.random.uniform(size=M)
>>> c = np.random.standard_normal(size=M) + 1j * np.random.standard_normal(size=M)
>>> f = nufft1(N, c, x, eps=1e-6, iflag=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax_finufft/ops.py", line 33, in nufft1
    result = nufft1_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: NotImplementedError: MLIR translation rule for primitive 'nufft1' not found for platform cuda

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 163, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/api.py", line 694, in cache_miss
    execute = dispatch._xla_call_impl_lazy(fun_, *tracers, **params)
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/dispatch.py", line 240, in _xla_call_impl_lazy
    return xla_callable(fun, device, backend, name, donated_invars, keep_unused,
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/linear_util.py", line 301, in memoized_fun
    ans = call(fun, *args)
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/dispatch.py", line 351, in _xla_callable_uncached
    computation = sharded_lowering(fun, device, backend, name, donated_invars,
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/dispatch.py", line 342, in sharded_lowering
    return pxla.lower_sharding_computation(
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2940, in lower_sharding_computation
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 725, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1007, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/home/ruiming/anaconda3/envs/gpu-jax-finufft/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1124, in jaxpr_subcomp
    raise NotImplementedError(
NotImplementedError: MLIR translation rule for primitive 'nufft1' not found for platform cuda
```

Do you know what would be the possible cause for this? Thanks!

**Comment by dfm** [comment]
This will happen if the GPU extensions don't get compiled. Can you post exactly which steps you're using to build and the full output of:

```bash
python -m pip install -v .
```

**Comment by lgarrison** [comment]
This could also happen if they're compiled but can't be imported, for
example if a shared library can't be found (did you set LD_LIBRARY_PATH per
the readme?).

**Comment by rmcao** [comment]
It turns out that the GPU compiler was not found initially according to the verbose output (even when the LD_LIBRARY_PATH was set). I searched on this and figured that I can add a flag "-DCMAKE_CUDA_COMPILER:PATH=/usr/local/cuda/bin/nvcc" to CMAKE_ARGS, which helps to find CUDA compiler at the end! 

@dfm @lgarrison Thank you for your help!
